server:
  port: 8081


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accounts_db
    username: root
    password:




  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true